### ISSUE TITLE
Implement PostCSS Autoprefixer and make sure browser support is accurate

### ISSUE THREAD

**Issue by chris-pearce** [kllevin/citychiropractor#16]
See CP for details on PostCSS Autoprefixer implementation.

Browser support should be:
- **Last 2 versions**
- **IE 10 and 11**
- **MS Edge** (not sure if this is included in the **Last 2 versions**?)

There's a `browserlist` file in the root which should reflect the above and Autoprefixer can read from that file.

**Comment by kllevin** [comment]
This should now utilise the browserslist config, instead of hardcoding the support into the grunt task.
