### ISSUE TITLE
Get Modernizr Grunt task working or roll custom feature detection

### ISSUE THREAD

**Issue by chris-pearce** [kllevin/citychiropractor#45]
We only need Modernizr to feature detect **Flexbox** & **Flexbox Tweener**. I think it's working looking into a custom script e.g.
- https://gist.github.com/branneman/5e4c23c8a9584f85410c
- http://stackoverflow.com/questions/26761298/detecting-flex-wrap-support-in-browsers

**Comment by chris-pearce** [comment]
Can we use this: http://johanronsse.be/2016/01/03/simple-flexbox-check/?

**Comment by chris-pearce** [comment]
Not sure if ^ supports FB tweener?

**Comment by kllevin** [comment]
I used modernizr for now. it's 5kb before minimized, we can decide after browser testing if we want to use something else instead.
